読破済み機能実装
yanbaru-expert/team_project_44 pull request #39
Opened 2021-04-03 09:31 UTC by yukimi-y

## 実装内容
- 読破済み機能の部分テンプレートを作成
    - 一覧ページ,詳細ページに読破済み機能を実装
- Bootstrap のボタンスタイルを利用
- 読破済み機能を非同期化

## 参考資料
- 読破済み機能
    - [やんばるCODE教材（モデルの関連付け その2(多対多)）](https://www.yanbaru-code.com/texts/297)
    - [【公式】Bootstrap（Button）](https://getbootstrap.jp/docs/4.5/components/buttons/)

2021-04-03 09:41 UTC, T-Tsujii requested changes

2021-04-03 09:41 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +  <%= render @texts %>
`<div class="row">` は繰り返し処理ではないのでここに残さないといけません。
`<%= render @texts %>` は row の中に入れなければなりません。

2021-04-03 09:41 UTC, T-Tsujii commented on app/views/texts/_text.html.erb
> +  <% @texts.each do |text| %>
`each` が不要になります。



```suggestion
```

2021-04-03 09:41 UTC, T-Tsujii commented on app/views/texts/_text.html.erb
> +</div>
```suggestion
```

2021-04-03 10:05 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-05 11:08 UTC, YokoyamaGen requested changes

2021-04-05 11:08 UTC, YokoyamaGen commented on app/models/user.rb
> +  has_many :texts
2行目は他の処理で使用されていないため、不要なコードだと思いました。

2021-04-05 11:08 UTC, YokoyamaGen commented on app/models/user.rb
> +  has_many :read_texts, through: :reads, source: :text
4行目は他の処理で使用されていないため、不要なコードだと思いました。

2021-04-05 11:08 UTC, YokoyamaGen commented on app/models/text.rb
> +  belongs_to :user
2行目は他の処理で使用されていないため、不要なコードだと思いました。

2021-04-05 11:08 UTC, YokoyamaGen commented on app/models/text.rb
> +  has_many :read_users, through: :reads, source: :user
4行目は他の処理で使用されていないため、不要なコードだと思いました。

2021-04-06 09:53 UTC, YokoyamaGen approved these changes
LGTMです！

2021-04-06 13:05 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-06 13:20 UTC, merged