テキスト詳細ページのデザイン修正
yanbaru-expert/team_project_44 pull request #41
Opened 2021-04-10 09:27 UTC by YokoyamaGen

close #40

## 実装内容

- コードブロックでシンタックスハイライトを使用するためにGem「Rouge」を導入する。
- Gem「Rouge」を導入するだけでなく、デザインをカスタマイズするために「_rouge.scss.erb」および「application.scss」にscssを追記する。

## 参考文献

- [RougeのGithub](https://github.com/rouge-ruby/rouge)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-12 13:12 UTC, T-Tsujii requested changes

2021-04-12 13:12 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +li a {
影響範囲の大きいスタイルの付け方は避けた方がよいですよ。

マークダウンに対してのみ反映させたいのであれば，`<p><%= markdown(@text.content) %></p>` にクラスを付けて対応できるでしょう。

2021-04-13 12:10 UTC, YokoyamaGen commented on app/assets/stylesheets/application.scss
> +li a {
ご指摘ありがとうございます。pタグでclassを記入してみたもののスタイルが上手くマークダウンに反映されなかったため、pタグからdivタグに変更することで、スタイルを上手く反映することができました。

2021-04-13 12:19 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-13 21:38 UTC, yukimi-y approved these changes
LGTMです。

2021-04-14 09:54 UTC, merged