質問一覧ページの実装
yanbaru-expert/team_project_44 pull request #44
Opened 2021-05-04 01:39 UTC by miya8021

close #37

## 実装内容
- questionsコントローラとビューファイル、ルーティングを作成
- 検索機能の ransack 導入、questionsコントローラーの設定
- ルーティングの再設定、コントローラーの修正、_header.html.erbによくある質問集へのリンクを追加
- jQueryのインストール - Webpackの設定、動作確認
- チェックボックスの作成・JavaScriptで絞り込み表示の設定
-  BootstrapとCSSでスタイルの調整

## 参考資料
- [Rails6でのjQuery導入方法](https://qiita.com/tatsuhiko-nakayama/items/b2f0c77e794ca8c9bd74)
- [やんばる教材 検索機能(Ransack)](https://www.yanbaru-code.com/texts/221)
- [jQueryで簡易的な検索機能(フィルター機能)を作る方法](https://mito-lab.com/jquery-selectitem/)
- [jQueryAPI ドキュメント](https://api.jquery.com/eq/)
- [jQueryのhtml()で追加・取得・書き換えの方法まとめ](https://www.sejuku.net/blog/38267)
- [Bootstrap レイアウト](https://getbootstrap.com/docs/5.0/forms/layout/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考
- 今回の実装で使用しなかったgem（gon）を導入していますが、削除した方がよろしいでしょうか？

2021-05-04 02:25 UTC, T-Tsujii requested changes

2021-05-04 02:25 UTC, T-Tsujii commented on Gemfile
> +gem 'gon'
結果的に使用していないので削って `bundle install` を実行して下さい

```suggestion
```

2021-05-04 04:21 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-11 13:20 UTC, YokoyamaGen approved these changes
LGTM

2021-05-12 13:40 UTC, merged